services:
  mongodb:
    image: mongo:latest
    container_name: tech-atlas-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - tech_atlas_local
    volumes:
      - db-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./.env:/.env
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DB_ROOT_USERNAME}:${DB_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    networks:
      - tech_atlas_local

  dashboard-ui:
    image: moosi312/tech-atlas-dashboard-ui
    container_name: tech-atlas-dashboard-ui
    restart: unless-stopped
    ports:
      - 4200:8080

  dashboard-be:
    image: moosi312/tech-atlas-dashboard-be
    container_name: tech-atlas-dashboard-be
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb:27017
      - DB_NAME=${DB_FE_DATABASE}
      - DB_USER=${DB_FE_R_USER}
      - DB_PASS=${DB_FE_R_PASS}
    ports:
      - 8080
    networks:
      - tech_atlas_local

  admin-ui:
    image: moosi312/tech-atlas-admin-ui
    container_name: tech-atlas-admin-ui
    restart: unless-stopped
    ports:
      - 4300:8080

  scraper-be:
    image: moosi312/tech-atlas-scraper-be
    container_name: tech-atlas-scraper-be
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb:27017
      - DB_PIPE_NAME=${DB_FE_DATABASE}
      - DB_PIPE_USER=${DB_RAW_RW_USER}
      - DB_PIPE_PASS=${DB_RAW_RW_PASS}
      - DB_RAW_NAME=${DB_FE_DATABASE}
      - DB_RAW_USER=${DB_RAW_RW_USER}
      - DB_RAW_PASS=${DB_RAW_RW_PASS}
    ports:
      - 8050:8080
    networks:
      - tech_atlas_local

  transformer-be:
    image: moosi312/tech-atlas-transformer-be
    container_name: tech-atlas-transformer-be
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb:27017
      - DB_PIPE_NAME=${DB_FE_DATABASE}
      - DB_PIPE_USER=${DB_RAW_RW_USER}
      - DB_PIPE_PASS=${DB_RAW_RW_PASS}
      - DB_RAW_NAME=${DB_FE_DATABASE}
      - DB_RAW_USER=${DB_RAW_RW_USER}
      - DB_RAW_PASS=${DB_RAW_RW_PASS}
      - DB_FE_NAME=${DB_FE_DATABASE}
      - DB_FE_USER=${DB_FE_RW_USER}
      - DB_FE_PASS=${DB_FE_RW_PASS}
    ports:
      - 8060:8080
    networks:
      - tech_atlas_local
  authentik-postgresql:
    env_file:
    - .env
    environment:
      POSTGRES_DB: authentik
      POSTGRES_PASSWORD: authentik
      POSTGRES_USER: authentik
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
    - database:/var/lib/postgresql/data
  authentik-server:
    command: server
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_SECRET_KEY: authentik
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.2.2}
    ports:
    - ${COMPOSE_PORT_HTTP:-9000}:9000
    - ${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    shm_size: 512mb
    volumes:
    - ./authentik-blueprint:/blueprints/tech-atlas
    - ./data:/data
    - ./custom-templates:/templates
  authentik-worker:
    command: worker
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_SECRET_KEY: authentik
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.2.2}
    restart: unless-stopped
    shm_size: 512mb
    user: root
    volumes:
    - ./authentik-blueprint:/blueprints/tech-atlas
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data:/data
    - ./certs:/certs
    - ./custom-templates:/templates

volumes:
  db-data:
  database:
    driver: local

networks:
  tech_atlas_local: 
    name: tech_atlas_local
