x-common-labels: &common-labels
  traefik.enable: "true"
  com.centurylinklabs.watchtower.enable: "true"

x-frontend: &frontend-defaults
  restart: unless-stopped
  networks:
    - traefik

x-backend: &backend-defaults
  restart: unless-stopped
  networks:
    - traefik
    - tech_atlas

x-common-env: &common-env
  MONGO_URL: mongodb:27017

x-oauth-env: &oauth-env
  OAUTH_ISSUER: ${OAUTH_ISSUER}
  OAUTH_AUDIENCE: ${OAUTH_AUDIENCE}
  OAUTH_JWKS: ${OAUTH_JWKS}

x-pipe-env: &pipe-env
  DB_PIPE_NAME: ${DB_PIPE_DATABASE}
  DB_PIPE_USER: ${DB_PIPE_USER_RW}
  DB_PIPE_PASS: ${DB_PIPE_PASS_RW}

x-raw-env: &raw-env
  DB_RAW_NAME: ${DB_RAW_DATABASE}
  DB_RAW_USER: ${DB_RAW_RW_USER}
  DB_RAW_PASS: ${DB_RAW_RW_PASS}

x-cache-env: &cache-env
  DB_CACHE_NAME: ${DB_CACHE_DATABASE}
  DB_CACHE_USER: ${DB_CACHE_USER_RW}
  DB_CACHE_PASS: ${DB_CACHE_PASS_RW}

x-fe-rw-env: &fe-rw-env
  DB_FE_DATABASE: ${DB_FE_DATABASE}
  DB_FE_RW_USER: ${DB_FE_RW_USER}
  DB_FE_RW_PASS: ${DB_FE_RW_PASS}

x-fe-r-env: &fe-r-env
  DB_NAME: ${DB_FE_DATABASE}
  DB_USER: ${DB_FE_R_USER}
  DB_PASS: ${DB_FE_R_PASS}

services:
  mongodb:
    image: mongo:latest
    container_name: tech-atlas-db-${VERSION_SLUG}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - tech_atlas
    volumes:
      - db-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./.env:/.env

  landing-page:
    <<: *frontend-defaults
    image: moosi312/tech-atlas-landing-page:${VERSION}
    container_name: tech-atlas-landing-page-${VERSION_SLUG}
    labels:
      <<: *common-labels
      traefik.http.routers.tech-atlas-landing-page-2026-08-0.rule: "Host(`${VERSION_SLUG}.${BASE_DOMAIN}`)"
      traefik.http.routers.tech-atlas-landing-page-2026-08-0.entrypoints: web

  dashboard-ui:
    <<: *frontend-defaults
    image: moosi312/tech-atlas-dashboard-ui:${VERSION}
    container_name: tech-atlas-dashboard-ui-${VERSION_SLUG}
    labels:
      <<: *common-labels
      traefik.http.routers.tech-atlas-dashboard-ui-2026-08-0.rule: "Host(`dashboard${DOMAIN_SLUG}.${BASE_DOMAIN}`) && (!PathPrefix(`/api`))"
      traefik.http.routers.tech-atlas-dashboard-ui-2026-08-0.entrypoints: web

  dashboard-be:
    <<: *backend-defaults
    image: moosi312/tech-atlas-dashboard-be:${VERSION}
    container_name: tech-atlas-dashboard-be-${VERSION_SLUG}
    environment:
      <<: [*common-env, *fe-r-env]
    labels:
      <<: *common-labels
      traefik.http.routers.tech-atlas-dashboard-be-2026-08-0.rule: "Host(`dashboard${DOMAIN_SLUG}.${BASE_DOMAIN}`) && PathPrefix(`/api`)"
      traefik.http.routers.tech-atlas-dashboard-be-2026-08-0.entrypoints: web

  admin-ui:
    <<: *frontend-defaults
    image: moosi312/tech-atlas-admin-ui:${VERSION}
    container_name: tech-atlas-admin-ui-${VERSION_SLUG}
    labels:
      <<: *common-labels
      traefik.http.routers.tech-atlas-admin-ui-2026-08-0.rule: "Host(`admin${DOMAIN_SLUG}.${BASE_DOMAIN}`) && (!PathPrefix(`/api`))"
      traefik.http.routers.tech-atlas-admin-ui-2026-08-0.entrypoints: web

  scraper-be:
    <<: *backend-defaults
    image: moosi312/tech-atlas-scraper-be:${VERSION}
    container_name: tech-atlas-scraper-be-${VERSION_SLUG}
    environment:
      <<: [*common-env, *pipe-env, *raw-env, *oauth-env]
    labels:
      <<: *common-labels
      traefik.http.routers.tech-atlas-scraper-be-2026-08-0.rule: "Host(`admin${DOMAIN_SLUG}.${BASE_DOMAIN}`) && PathPrefix(`/api/scraper`)"
      traefik.http.routers.tech-atlas-scraper-be-2026-08-0.entrypoints: web

  transformer-be:
    <<: *backend-defaults
    image: moosi312/tech-atlas-transformer-be:${VERSION}
    container_name: tech-atlas-transformer-be-${VERSION_SLUG}
    environment:
      <<: [*common-env, *pipe-env, *raw-env, *oauth-env, *cache-env, *fe-rw-env]
    labels:
      <<: *common-labels
      traefik.http.routers.tech-atlas-transformer-be-2026-08-0.rule: "Host(`admin${DOMAIN_SLUG}.${BASE_DOMAIN}`) && PathPrefix(`/api/transformer`)"
      traefik.http.routers.tech-atlas-transformer-be-2026-08-0.entrypoints: web

networks:
  tech_atlas:
    name: tech_atlas_${VERSION_SLUG}
  traefik:
    name: traefik
    external: true

volumes:
  db-data:
    name: db-data_${VERSION_SLUG}
